#!/usr/bin/env bash
# script that displays numbers from 1 to 100.

NUMBER=1
while [ $NUMBER -le 100 ]
do
	if [ $((NUMBER % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $(( NUMBER % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((NUMBER % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo $NUMBER
	fi
	((NUMBER++))
done
