#!/usr/bin/env bash
# Script to print Best School 10 times

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo -n "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
