#!/usr/bin/env bash
# Script to print Best School 10 times

counter=1
while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from china"
			;;
		9)
			echo $counter
			echo "bad luck from japan"
			;;
		17)
			echo $counter
			echo "Best School"
			;;
		*)
			echo $counter
			;;
	esac
			((counter++))			
done
