#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

Hours=0
while [ $Hours -lt 13 ]
do
	echo "Hour: $Hours"
	minutes=1
	while [ $minutes -lt 60 ]
	do
		echo $minutes
		((minutes++))
	done
	((Hours++))
done
